"""add_session_cognitive_columns

Revision ID: 51134d935351
Revises: 264963ca7e56
Create Date: 2026-08-14 16:10:06.879916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51134d935351'
down_revision: Union[str, Sequence[str], None] = '264963ca7e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('emotional_summary', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('cognitive_summary', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('behavioral_summary', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('dominant_emotion', sa.String(length=50), nullable=True))
    op.add_column('sessions', sa.Column('risk_level', sa.String(length=20), nullable=True))
    op.add_column('sessions', sa.Column('risk_score', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('conversation_goal', sa.String(length=50), nullable=True))
    op.add_column('sessions', sa.Column('engagement_score', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('trust_score', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('openness_score', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('message_count', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('assistant_message_count', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('user_message_count', sa.Integer(), nullable=True))
    op.add_column('sessions', sa.Column('session_status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'session_status')
    op.drop_column('sessions', 'user_message_count')
    op.drop_column('sessions', 'assistant_message_count')
    op.drop_column('sessions', 'message_count')
    op.drop_column('sessions', 'openness_score')
    op.drop_column('sessions', 'trust_score')
    op.drop_column('sessions', 'engagement_score')
    op.drop_column('sessions', 'conversation_goal')
    op.drop_column('sessions', 'risk_score')
    op.drop_column('sessions', 'risk_level')
    op.drop_column('sessions', 'dominant_emotion')
    op.drop_column('sessions', 'behavioral_summary')
    op.drop_column('sessions', 'cognitive_summary')
    op.drop_column('sessions', 'emotional_summary')
    op.drop_column('sessions', 'summary')
    # ### end Alembic commands ###
